# Generated by Django 5.1.7 on 2025-03-27 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('description', models.TextField()),
                ('scraped_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
